Source/AlphaTab/Importer/AlphaTexImporter.cs

Proposed fix regards issue : #73 (AlphaText Importer reports error when Metadata tags are used).  
Tested against file included with issue and works as expected.

Changes to AlphaTex import to resolve MetaData Issue

---

Source/AlphaTab.Test/Audio/MidiPlaybackControllerTest.cs
Source/AlphaTab.Test/Importer/AlphaTexImporterTest.cs
Source/AlphaTab/Importer/AlphaTexImporter.cs

Fixed wrong repeat group generation for alphaTex

---

Source/AlphaTab/Audio/Synth/MidiFileSequencer.cs
Source/AlphaTab/Audio/Synth/Synthesis/TinySoundFont.AlphaTab.cs

Ensure mix volume is not reset on seeking

---

Source/AlphaTab.Test/Importer/AlphaTexImporterTest.cs
Source/AlphaTab/Importer/AlphaTexImporter.cs

Ensure correct display transposition pitches on alphaTex

---

Documentation/input/alphatex/beat-effects.cshtml
Source/AlphaTab.Test.Js/test/alphaTab.tests.specs.js
Source/AlphaTab.Test/Importer/AlphaTexImporterTest.cs
Source/AlphaTab/Importer/AlphaTexImporter.cs

Add dynamics support to alphaTex

---

Source/AlphaTab.JavaScript/UI/BrowserUiFacade.cs

Use document.scrollingElement for html/body scrolling

---

src/platform/javascript/AlphaSynthWebWorkerApi.ts
src/synth/AlphaSynth.ts

Remove some checks to allow starting player without soundfont loaded.

---

src/synth/MidiFileSequencer.ts
src/synth/synthesis/TinySoundFont.ts

Compute metronome ticks before updating tempo

---

package.json

This fixes the error with npm/yarn build.

fix error on yarn build #423

---

src/synth/synthesis/TinySoundFont.ts

Ensure metronome is playing along solo tracks

---

src/platform/javascript/AlphaTabApi.ts
src/platform/javascript/JQueryAlphaTab.ts

Fixes #469
Respects the current settings and allows users to specify additional ones for printing.

Print Settings

---

src/platform/javascript/AlphaSynthWebWorkerApi.ts
src/synth/AlphaSynth.ts
src/synth/SynthConstants.ts

Fixes #453
Remove the max volume limitation.

Remove max volume limitation

---

src/rendering/glyphs/ChordDiagramGlyph.ts
src/rendering/glyphs/VoiceContainerGlyph.ts

Fixes some scale factor related issues. 
Correctly respect scale factor at main layouting and chord diagrams.

Fixed some scaling issue

---

src/midi/AlphaSynthMidiFileHandler.ts
test/audio/MidiFileGenerator.test.ts

Fixes #567
Fixes the wrong time signature genaration (and adds a test for it)

Corrected timesignature generation 

---

.github/dependabot.yml
.github/workflows/dependabot.yml
.github/workflows/publish.yml

1. improves a bit the configuration and workflows with dependabot
2. switches to a nightly build approach for alpha builds (only if there are changes)

Configure dependabot and switch to nightly builds

---

src/AlphaTabApiBase.ts

Remove debugger statement

---

src/platform/javascript/AlphaTabApi.ts

Fixes #810
The absolute positioning does not play well with printing in most browsers. Luckily the browser default layouting fits quite well our needs for placing the elements. It's not fully perfect but printing seems fine in most browser with the new behavior: 
* We disable absolute positioning through CSS
* Added proper window title
* Use worker based rendering for smoother experience and proper webfont rendering
*

Improve handling of printing

---

src/rendering/index.ts
src/synth/index.ts

Fixes #897
Exposes some more APIs needed to use low level functionalities.

Expose some more APIs

---

src.compiler/kotlin/KotlinAstPrinter.ts
src.kotlin/alphaTab/alphaTab/build.gradle.kts
src.kotlin/alphaTab/build.gradle.kts
src.kotlin/alphaTab/gradle.properties

Fixes (no issues)
Manual upgrade of some dependabot packages.

Update Kotlin version

---

src/alphatab.ts
src/platform/index.ts

Export some more internal APIs.

Export more internals

---

package-lock.json
package.json
src.csharp/AlphaTab.Test/AlphaTab.Test.csproj
src.csharp/AlphaTab.Windows/AlphaTab.Windows.csproj
src.csharp/AlphaTab/AlphaTab.csproj
src.kotlin/alphaTab/alphaTab/build.gradle.kts
src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidAudioWorker.kt
src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidEnvironment.kt
src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidRootViewContainer.kt
src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidUiFacade.kt
src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidViewContainer.kt
src.kotlin/alphaTab/alphaTab/src/androidUnitTest/kotlin/alphaTab/visualTests/VisualTestHelperPartials.kt
src.kotlin/alphaTab/gradle/libs.versions.toml

Fixes #1152
- Integrates the latest alphaSkia with various bugfixes around Android rendering (vertically tested now). 
- There were problems in the font manager and some unsafe code paths on text shaping. 
- JNI lib loading now works (normal Java Resources are stripped on Android apps, moved to Android defaults with an AAR)
- A new sample writing thread was wrongly started on every play (fixes #1152)
- It could happen on debouncing/throttling of calls that a background coroutine thread accesses the UI components leading to exceptions.

Fix various Android problems

---

package-lock.json
package.json
rollup.config.cjs.ts
rollup.config.ts
rollup.plugin.server.ts
src/Environment.ts
src/alphaTab.main.ts

Fixes #1400
With the rework for WebPack the CJS flavor wasn't starting up correctly anymore due to the missing initialization code.

Fix CommonJS (all-in-one) build 

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/dependabot.yml
.github/workflows/publish.yml
.github/workflows/release.yml
README.md
src.csharp/AlphaTab.Test/AlphaTab.Test.csproj
src.csharp/AlphaTab.Windows/AlphaTab.Windows.csproj

#1464
Bump target compilation to net8.0

chore: Target net8.0

---

.github/workflows/release.yml
scripts/update-kotlin-version.js

build: Prepare Kotlin Release pipeline

---

.github/workflows/publish.yml
package.json
scripts/update-kotlin-version.js
src.kotlin/alphaTab/android/build.gradle.kts

Fixes some errors on the current publish workflow.

build: Fix publishing errors

---

vite.config.ts

Fixes #2028
Fixes the mentioned problems.

build: Using statement and import path rewriting

---

LICENSE.header
vite.config.ts

Prepares some things for the release.

chore: Release preparations

---

src/AlphaTabApiBase.ts
src/model/ModelUtils.ts
src/rendering/ScoreRendererWrapper.ts
src/rendering/layout/ScoreLayout.ts
src/rendering/staves/StaffSystem.ts

Fixes various small bits where dynamic changes of settings were not resulting in the correct behavior.

fix: Ensure dynamic changes of settings are respected

---

playground-template/youtube.html
src.compiler/AstPrinterBase.ts
src.compiler/csharp/CSharpAst.ts
src.compiler/csharp/CSharpAstPrinter.ts
src.compiler/csharp/CSharpAstTransformer.ts
src.compiler/kotlin/KotlinAstPrinter.ts
src/AlphaTabApiBase.ts
src/exporter/Gp7Exporter.ts
src/exporter/GpifWriter.ts
src/importer/GpifParser.ts
src/midi/MidiFileGenerator.ts
src/model/Automation.ts
src/model/Score.ts
src/model/_barrel.ts
src/platform/javascript/AudioElementBackingTrackSynthOutput.ts
src/synth/AlphaSynthWrapper.ts
src/synth/ExternalMediaPlayer.ts
src/synth/MidiFileSequencer.ts
src/synth/_barrel.ts
src/xml/XmlNode.ts
src/xml/XmlWriter.ts
test/exporter/Gp7Exporter.test.ts
test/xml/XmllWrite.test.ts

Relates to #2083 
Various adjustments and extensions as needed for the new external cursor API.

feat: Public API for External Media Control

---

src/webpack/AlphaTabAudioWorklet.ts
src/webpack/AlphaTabWebWorker.ts
test/bundler/WebPack.test.ts

fix(webpack): Prevent worker chunks using global library settings
