CoderLine/alphaTab

- Samples/JavaScript/lib/alphaSynth/AlphaSynth.worker.js
- Samples/JavaScript/player.html
Windows is not register-dependent but Linux (unix) is not.
There could be more, was just running player.html to ensure it works (it worked after the change).
> fixed register in some names to fix player call

- Documentation/input/reference/api/loadsoundfont.cshtml
- Source/AlphaTab.CSharp/Platform/CSharp/ManagedUiFacade.cs
- Source/AlphaTab.CSharp/Platform/CSharp/WinForms/WinFormsUiFacade.cs
- Source/AlphaTab.CSharp/Platform/CSharp/Wpf/WpfUiFacade.cs
- Source/AlphaTab.JavaScript/UI/BrowserUiFacade.cs
- Source/AlphaTab/AlphaTabApi.cs
- Source/AlphaTab/UI/IUiFacade.cs
Fixes #293 
This PR ensures the player is dynamically enabled and destroyed based on the settings when calling `updateSettings`
> Add dynamic enable/disable of player and cursor feature

- Source/AlphaTab.JavaScript/UI/BrowserUiFacade.cs
> Fix scrolling on mobile devices

- Source/AlphaTab.JavaScript/Environment.cs
- Source/AlphaTab.JavaScript/Platform/JavaScript/AlphaSynthWebWorkerApi.cs
- Source/AlphaTab.JavaScript/Platform/JavaScript/AlphaTabWorkerScoreRenderer.cs
Fixes #304 
Firefox has some weird behavior on worker creations in CORS scenarios. Blob workers with importScripts seem to work and it does not break anything on other browsers.
> Create workers via blobs by default

- Source/AlphaTab.JavaScript/UI/BrowserUiFacade.cs
Fixes #299 
Related to #303
Some basic tests have shown it is not necessary to decouple the logic of appending render results to the DOM from the receive event of workers. Workers will continue processing independent and not block on postMessage. For non-worker usage, decoupling anyhow brings no benefit.
> Remove decoupling of render result appending

- Source/AlphaTab/Audio/MidiTickLookup.cs
- Source/AlphaTab/Rendering/BarRendererFactory.cs
- Source/AlphaTab/Rendering/EffectBarRendererFactory.cs
- Source/AlphaTab/Rendering/Staves/Staff.cs
- Source/AlphaTab/Rendering/Staves/StaveGroup.cs
- Source/AlphaTab/Rendering/Staves/StaveTrackGroup.cs
- appveyor.yml
fixes #318 
This PR changes 2 parts of the cursor handling: 
1. The duration of the cursor movement considers now the tick of the nextBeat 
2. The bounds lookup is now filled with with all staves that are relevant for the position handling
> Fixed jumping on cursor for multi staff setups

- Source/AlphaTab/AlphaTabApi.cs
- Source/AlphaTab/Audio/Generator/MidiFileGenerator.cs
- Source/AlphaTab/Audio/MidiTickLookup.cs
fixes #216 
Added a new cache in the tick lookup which keeps track on which beats to highlight. This costs a bit on the midi tick lookup generation but it is still feasable.
> Add support for multi staff / track note highlighting

- Documentation/input/alphatex/beat-effects.cshtml
- Source/AlphaTab.Test/Importer/AlphaTexImporterTest.cs
- Source/AlphaTab/Importer/AlphaTexImporter.cs
> Add support for crescendo and decrescendo in alphaTex

- Source/AlphaTab/Rendering/Glyphs/TieGlyph.cs
> Handle missing startNoteRenderer due to partial renders

- Source/AlphaTab.JavaScript/Platform/JavaScript/AlphaSynthWebWorkerApi.cs
fixes #290 
Web Audio context instances are nowadays suspended for most browsers. They only can be activated within an event triggered by user interaction. PlayPause was missing this activation.
> Added missing player activation

- Source/AlphaTab.Test/Importer/AlphaTexImporterTest.cs
- Source/AlphaTab/Importer/AlphaTexImporter.cs
> Reset dynamics on staves and tracks back to default

- Directory.Build.props
- Documentation/input/reference/events/beatmousedown.cshtml
- Documentation/input/reference/events/beatmousemove.cshtml
- Documentation/input/reference/events/beatmouseup.cshtml
- Documentation/input/reference/property/player-enableuserinteraction.cshtml
- Source/AlphaTab.CSharp/Platform/CSharp/ManagedUiFacade.cs
- Source/AlphaTab.CSharp/Platform/CSharp/WinForms/WinFormsUiFacade.cs
- Source/AlphaTab.CSharp/Platform/CSharp/Wpf/WpfUiFacade.cs
- Source/AlphaTab.JavaScript/UI/BrowserMouseEventArgs.cs
- Source/AlphaTab.JavaScript/UI/BrowserUiFacade.cs
- Source/AlphaTab/AlphaTabApi.cs
- Source/AlphaTab/Settings.cs
- Source/AlphaTab/UI/IUiFacade.cs
- appveyor.yml
Fixes #349 
Also adds mouse events related to beats (mousedown, move, up) to build potenatially a custom selection mechanism.
> Setting to disable default user interaction

- package.json
- src/PlayerSettings.ts
- src/midi/MidiFileGenerator.ts
- src/model/Note.ts
> Add audio generation for slides

- src/midi/AlphaSynthMidiFileHandler.ts
- src/midi/IMidiFileHandler.ts
- src/midi/Midi20ChannelVoiceEvent.ts
- src/midi/MidiEvent.ts
- src/midi/MidiFileGenerator.ts
- src/model/JsonConverter.ts
- src/synth/SynthConstants.ts
- src/synth/synthesis/Channel.ts
- src/synth/synthesis/Channels.ts
- src/synth/synthesis/TinySoundFont.ts
- src/synth/synthesis/Voice.ts
- test/audio/FlatMidiEventGenerator.ts
- test/audio/MidiFileGenerator.test.ts
> Added a per-note pitch bend event and used it on various effects.

- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedUiFacade.cs
- src.csharp/Samples/AlphaTab.Samples.Player/Program.cs
- src/AlphaTabApiBase.ts
- src/platform/IUiFacade.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaTabApi.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/JQueryAlphaTab.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/synthesis/Preset.ts
- src/synth/synthesis/TinySoundFont.ts
- src/synth/synthesis/Voice.ts
- test/audio/AlphaSynth.test.ts
> Multiple Soundfont support

- src/AlphaTabApiBase.ts
> Update selection cursor when setting playbackRange.

- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src/platform/javascript/AlphaSynthWebAudioOutput.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaSynthWorkerSynthOutput.ts
- src/synth/AlphaSynth.ts
- src/synth/ISynthOutput.ts
- src/synth/MidiFileSequencer.ts
- src/synth/SynthConstants.ts
- src/synth/synthesis/TinySoundFont.ts
- src/synth/synthesis/Voice.ts
- test/audio/TestOutput.ts
Resolves #410
- Moved looping and finish logic to time update handler
- Moved microbuffer looping from synth to higher level
- Ensure break on synth when end is reached.
> Rework looping logic

- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src/AlphaTabApiBase.ts
- src/midi/MidiFileGenerator.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/MidiFileSequencer.ts
- src/synth/PlayerState.ts
> Add mechanism to play a single beat and note

- src/model/Track.ts
When reading that file, alphaTab crash because lyrics is at bar 126 but there's only 108 bars. With the fix, lyrics placed after last bar is ignored.
[The Cranberries - Zombie (ver 7 by kartapus).zip](https://github.com/CoderLine/alphaTab/files/5597576/The.Cranberries.-.Zombie.ver.7.by.kartapus.zip)
> Fix crash when lyrics startBar is over bars length

- playground-template/control-template.html
- playground-template/control.js
- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src/AlphaTabApiBase.ts
- src/platform/javascript/AlphaSynthWebAudioOutput.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/JQueryAlphaTab.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/MidiFileSequencer.ts
- src/synth/synthesis/TinySoundFont.ts
> Add a count-in option

- src/rendering/TabBarRenderer.ts
- src/rendering/glyphs/NoteNumberGlyph.ts
- src/rendering/glyphs/VoiceContainerGlyph.ts
Fixes #452
Consider correctly the scale level at some required places.
> Fixed some zoom related issues.

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #449
Adds an autodetection of the right tuning for a set of instruments.
> Improved detection of instrument and tuning in alphaTex

- src/midi/MidiFileGenerator.ts
- test/audio/MidiFileGenerator.test.ts
Fixes #470
Corrects some bend generations by using always the note-bend events for note height related changes.
> Fix wrong bend sounds

- src/Environment.ts
- src/platform/javascript/Html5Canvas.ts
- test/visualTests/VisualTestHelper.ts
Fixes #496
Detect the HighDPI displays and render images in the corresponding scale.
> Add high DPI scaling for HTML5 canvas for better display

- src.compiler/typescript/SerializerEmitter.ts
- src/generated/NotationSettingsSerializer.ts
- src/generated/model/MasterBarSerializer.ts
- src/generated/model/StaffSerializer.ts
Fixes #500
Use `JsonHelper.forEach` to iterate object/map objects correctly when parsing JSON.
> Fixed map parsing on JSON serializer

- src/importer/CapellaParser.ts
- src/importer/MusicXmlImporter.ts
- src/model/Beat.ts
- test-data/musicxml3/full-bar-rest.musicxml
- test/audio/MidiFileGenerator.test.ts
- test/importer/MusicXmlImporter.test.ts
- test/importer/MusicXmlImporterTestSuite.test.ts
Fixes #495
Adds full-bar-rest handling to the data model, file importers and midi generator.
> Add support for full-bar rests

- src/CoreSettings.ts
- src/generated/CoreSettingsSerializer.ts
- src/platform/javascript/BrowserUiFacade.ts
- test/model/JsonConverter.test.ts
Fixes #510
1. Replaces the old timer based visibility checker with the IntersectionObserver 
2. Replaces the `getBoundingClientRect` based lazy loading system with the IntersectionObserver
> Add IntersectionObserver for initial load and lazy loading

- package-lock.json
- package.json
- src.csharp/AlphaTab.Windows/WinForms/ControlContainer.cs
- src.csharp/AlphaTab.Windows/Wpf/FrameworkElementContainer.cs
- src/Environment.ts
- src/platform/IContainer.ts
- src/platform/javascript/HtmlElementContainer.ts
- src/platform/javascript/ResizeObserverPolyfill.ts
Fixes #511
Uses the Resize Observer if available instead of the window resize event.
> Added usage of resize observer if available.

- src.compiler/csharp/CSharpAst.ts
- src.compiler/csharp/CSharpAstPrinter.ts
- src.compiler/csharp/CSharpAstTransformer.ts
- src.csharp/AlphaTab.Windows/DelegatedEventEmitter.cs
- src.csharp/AlphaTab/EventEmitter.cs
- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src/AlphaTabApiBase.ts
- src/EventEmitter.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/PositionChangedEventArgs.ts
Fixes #520
Adds some internal synth info to the events which allows easier synchronization of the synthesizer with an external audio source.
> Added some event data for easier sync with audio.

- src/Environment.ts
- src/platform/javascript/AlphaSynthWebAudioOutput.ts
- src/platform/javascript/AlphaTabWebWorker.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/WebPlatform.ts
Fixes #542
Adds some checks to detect node.js and avoids accessing browser specific APIs.
> Handle node.js environment correctly

- src/model/Color.ts
- test/model/Color.test.ts
Fixes #387 
Updates the `substring` logic in `Color.ts` to properly grab the RGB values. Without this change `numbers` ends up being an array w/ a single item in it with eventually causes the method to return `null`.
> Add Basic Color Test for RGB

- src/Environment.ts
- src/platform/javascript/IntersectionObserverPolyfill.ts
- src/platform/svg/SvgCanvas.ts
added polyfill for intersectionobserver and handle dominant-baseline correctly.
Fixes #556 
Apply dominant-baseline via CSS style and add polyfill for IntersectionObserver (iOS 11 compat)
> Fixed iOS related display issues

- package-lock.json
- package.json
- src.csharp/Directory.Build.props
- src/Environment.ts
- src/platform/javascript/IntersectionObserverPolyfill.ts
- src/platform/svg/SvgCanvas.ts
- src/rendering/glyphs/ChordDiagramGlyph.ts
- src/rendering/glyphs/VoiceContainerGlyph.ts
This PR backports some fixes on 1.3 to 1.2: 
1. iOS 11 compatibility and alignment issues
2. Scaling related issues
> Release 1.2.1

- src.compiler/csharp/CSharpAstPrinter.ts
- src.compiler/kotlin/KotlinAstPrinter.ts
- src.csharp/AlphaTab/AlphaTab.csproj
- src.csharp/Directory.Build.props
- src/AlphaTabApiBase.ts
- src/importer/AlphaTexImporter.ts
- src/io/ByteBuffer.ts
- test/TestPlatform.ts
- test/audio/AlphaSynth.test.ts
- test/audio/MidiFileGenerator.test.ts
- test/audio/MidiPlaybackController.test.ts
- test/exporter/Gp7Exporter.test.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #579 
Use TextEncoder when creating a ByteBuffer from a string and for alphaTex even pass on the string directly.
> Add unicode support to alphaTex

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #581
Treat empty bar metadata as error.
> Fix hanging alphaTex import on backslash

- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src/AlphaTabApiBase.ts
- src/platform/javascript/AlphaSynthWebAudioOutput.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaSynthWorkerSynthOutput.ts
- src/synth/AlphaSynth.ts
- src/synth/ISynthOutput.ts
- test/audio/TestOutput.ts
Fixes #594
Extends the destroy sequence to first shutdown the synth output.
> Fully destroy alphaTab player

- src.csharp/AlphaTab.Test/VisualTests/VisualTestHelper.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedThreadScoreRenderer.cs
- src.kotlin/alphaTab/src/jvmTest/kotlin/alphaTab/visualTests/VisualTestHelperPartials.kt
- src/model/Beat.ts
- src/model/GraceGroup.ts
- src/model/Voice.ts
Fixes #551
This PR ensures the model is consistent and correctly filled directly after loading+finish call. Previously there were some inconsistencies which only were sorted out by serializing+deserializing the data model.
> Fixed model inconsistencies without serialization

- src.csharp/AlphaTab.Windows/WinForms/ControlContainer.cs
- src.csharp/AlphaTab.Windows/WinForms/WinFormsUiFacade.cs
- src.csharp/AlphaTab.Windows/Wpf/FrameworkElementContainer.cs
- src.csharp/AlphaTab.Windows/Wpf/WpfUiFacade.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedUiFacade.cs
- src/AlphaTabApiBase.ts
- src/PlayerSettings.ts
- src/generated/PlayerSettingsSerializer.ts
- src/platform/IContainer.ts
- src/platform/IUiFacade.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/HtmlElementContainer.ts
Relates to #558 
This PR optimizes various parts of the cursor positioning and optimizes some browser actions. It also adds some settings to disable performance intense features like animated cursors and element highlighting.
> Browser optimizations 

- src/AlphaTabApiBase.ts
- src/midi/BeatTickLookup.ts
- src/midi/MasterBarTickLookup.ts
- src/midi/MidiTickLookup.ts
- src/platform/javascript/AlphaSynthAudioWorkletOutput.ts
- src/platform/javascript/BrowserUiFacade.ts
Fixes #558 
We remember the tick lookup and consider this info on cursor changes to efficiently select the next beat.
> Try to respect current and known next beat on cursor changes.

- src.csharp/AlphaTab.Windows/WinForms/ControlContainer.cs
- src.csharp/AlphaTab.Windows/Wpf/FrameworkElementContainer.cs
- src/AlphaTabApiBase.ts
- src/platform/IContainer.ts
- src/platform/javascript/HtmlElementContainer.ts
Fixes #648
Fixes a newly introduced issue where in FireFox the cursor was flickering back sometimes. This was due to some animation timing issue. One of the previously introduced optimizations does not play well with these animations so I had to remove it again.
> Fixed flickering of beat cursor in firefox

- src/platform/javascript/AlphaSynthAudioWorkletOutput.ts
Fixes #646
Safari does not allow accessing the members of `AudioWorkletGlobalScope` through `globalThis` even though it provides it. It results in errors to do so. Therefore we need to ensure in alphaTab to not use `globalThis` to access the `sampleRate` and `registerProcessor`.
Using globalThis results in errors like: 
> TypeError: Can only call AudioWorkletGlobalScope.registerProcessor on instances of AudioWorkletGlobalScope
> Fix audio worklets in safari

- package-lock.json
- package.json
- src.csharp/Directory.Build.props
- src/Settings.ts
> Release 1.2.2

- package.json
- rollup.config.js
- src/Environment.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaTabWorkerScoreRenderer.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/WebPlatform.ts
Fixes #666
1. Adds detection on whether alphaTab is imported using ES6 modules and resolves the current script url accordingly
2. Adds ES6 module compilation output for usage in ES6 modules within the browser and respective handling on the workers.
> Add ES6 module compilation

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #683
Ignore note specific symbols when interpreting optional section text/marker combination in alphaTex
> Ensure we don't interpret note symbols as section text

- src/synth/AlphaSynth.ts
Fixes #657 
We need to reset the already buffered audio in case we make any audio related changes like muting tracks or changing volumes. Otherwise it can take a while until it gets applied. 
We do this clearing by simply seeking to the currently known time position. This will clear anything in the output buffers and trigger a regeneration of the audio.
> Clear buffered samples on audio settings change

- src/AlphaTabApiBase.ts
- src/model/Score.ts
- src/rendering/ScoreRenderer.ts
- src/rendering/layout/HorizontalScreenLayout.ts
- src/rendering/layout/PageViewLayout.ts
- src/rendering/layout/ScoreLayout.ts
- src/rendering/staves/StaveGroup.ts
- src/synth/MidiFileSequencer.ts
- src/synth/soundfont/Hydra.ts
Fixes various issues introduced on #692
There were some issues introduced with #692 which were already fixed on #612 this PR already integrates them independent from the Android features.
> Adapt fixes from android branch

- src/rendering/utils/BeatBounds.ts
Fixes #744
Fixes logic on `findNoteAtPos` to correctly find the expected note. Here is a simple codepen demonstrating the fix:
https://codepen.io/gallegretti/pen/KKyqypL
As you click on the notes, the ids will be logged on the console
> Fix findNoteAtPos logic

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- README.md
- src.csharp/AlphaTab.Test/AlphaTab.Test.csproj
- src.csharp/AlphaTab.Windows/AlphaTab.Windows.csproj
Fixes (none)
Updated some outdated information on the readme and enriched it a bit. Also dropped .netcore 3.x and .net 5 support in favor of .netstandard2.0 (Core) and .net6.0-windows (Windows)
> Update readme and targeted versions

- src/Environment.ts
- src/platform/javascript/BrowserUiFacade.ts
Relates to #759 
Adds detection for WebPack bundling and 
1. activates WebPack compatible WebWorker creation
2. Disabling of Audio Worklets as they are currently not supported.
> Improve WebPack Support (Step 1)

- src/platform/javascript/AlphaSynthWebAudioOutputBase.ts
- src/platform/javascript/AlphaTabApi.ts
Relates to #760 
Improves the handling of the audio context. In some React tests it turned out that we might access a closed Audio Context. This PR improves this situation.
> Improve handling of audio context and related promise handling

- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidThreadAlphaSynthWorkerPlayer.kt
- src/AlphaTabApiBase.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/PlaybackRangeChangedEventArgs.ts
- src/synth/index.ts
Relates to #732
Exposes a new event which is fired whenever the playback range in the player updates.
> Added event for changed playback ranges.

- src/AlphaTabApiBase.ts
> Fix wrong comparison of start/end in reverse selection scenarios

- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidAudioWorker.kt
- src/AlphaTabApiBase.ts
- src/midi/MidiFileGenerator.ts
- src/platform/javascript/AlphaSynthAudioWorkletOutput.ts
- src/platform/javascript/AlphaSynthScriptProcessorOutput.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/rendering/RenderFinishedEventArgs.ts
- src/rendering/glyphs/NoteNumberGlyph.ts
- src/rendering/layout/PageViewLayout.ts
- src/rendering/utils/BoundsLookup.ts
- src/synth/AlphaSynth.ts
- src/synth/MidiFileSequencer.ts
Fixes #758
Reworks quite some internals of the synthesizer to ensure that the one time midi playback behind playBeat and playBeat are working correctly. it suffered from following issues: 
- Seeking during playback interfered with the playback position of the one time midi while it should seek on the main song midi. When playing notes/beats on mouse click, there happened a playback and seeking which messed up a lot of internals. 
- Multiple subsequent requests of playing one time midis before they actually finished also messed up some internal states. 
- The synth outputs reported also played samples if there weren't enough samples in the buffer. This wrongly advanced the internal player time axis. 
- The bounds lookup had a wrong assumption that there is only one bounds for a beat, but …
> Rework state handling of one-time-midi

- src.csharp/AlphaTab/Platform/CSharp/SkiaCanvas.cs
Fixes #774
As discussed in https://github.com/CoderLine/alphaTab/pull/775 Since 2.80.0 SkiaSharp is loading properly the native libs internally. We don't need our custom code.
> Drop manual loading of native Skia lib

- karma.conf.js
- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedThreadAlphaSynthWorkerApi.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedUiFacade.cs
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidSynthOutput.kt
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidThreadAlphaSynthWorkerPlayer.kt
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidUiFacade.kt
- src/PlayerSettings.ts
- src/generated/PlayerSettingsSerializer.ts
- src/platform/javascript/AlphaSynthAudioWorkletOutput.ts
- src/platform/javascript/AlphaSynthScriptProcessorOutput.ts
- src/platform/javascript/AlphaSynthWebAudioOutputBase.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/synth/AlphaSynth.ts
- src/synth/ISynthOutput.ts
- test/audio/AlphaSynth.test.ts
- test/audio/TestOutput.ts
Fixes #736
Exposes a new setting which makes the audio buffering configurable. This should allows integrators to optimize the buffering for their devices. Default is reduced to 500ms which should provide a good experience between delay on setting updates, and no crackling sounds due to buffering
> Make audio buffer configurable

- src/platform/javascript/AlphaTabApi.ts
Fixes #844
Actually #844 had a wrong assumption that we have double render events on load. But this problem was already addressed in 1.3 and it is not reproducible anymore. But we had the issue that during print we do not clear some settings which must be cleared for printing. Due to this we first rendered the tracks as displayed currently, and then the default file loading kicked in and rendered it again.
> Clear various settings during print to avoid double print.

- src/Environment.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaTabWorkerScoreRenderer.ts
Relates to #759
Move the check for a detected scriptfile so that in WebPack cases it does not need to be set.
> Centralize worker creation logic and improved webpack handling

- src/Environment.ts
Fixes #836
It seems some older iOS / iPadOS versions don't support `Element.replaceChildren`. Added a polyfill.
> Add replaceChildren polyfill for older iOS versions

- src/importer/AlphaTexImporter.ts
- test/audio/MidiPlaybackController.test.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #671 
The `\ae` bar meta tag for alphaTex can be used to mark bars as alternate endings in a repeat.
Syntax examples: `\ae (1 2 3)` and `\ae 4`.
- Two tests for parsing the tag.
- A new test for `MidiPlaybackController` added but needs a fix for passing. 
- *I can write a section for this once the feature has been released.*
> alphaTex Alternate Endings

- src.csharp/AlphaTab.Windows/WinForms/WinFormsUiFacade.cs
- src.csharp/AlphaTab.Windows/Wpf/WpfUiFacade.cs
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/AlphaTabView.kt
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidUiFacade.kt
- src/AlphaTabApiBase.ts
Fixes #876
* Adds  dynamic enabling/disabling of cursors. 
* Adds dynamic color changing on `UpdateSettings` call
> Enable / disable cursor after alphaTab is loaded

- src/synth/AlphaSynth.ts
- src/synth/MidiFileSequencer.ts
Fixes #931
There were some problems with the switching of count-in and one-time midis back to the main song for Audio Worklets. As we never replied to a sample request to the output, it just could hang at some point and loose those requests. We now reply to all requests with a buffer (empty in case sequencer is done). 
Beside that there was also a wrong seeking to the main song position after count in because it did not respect the playback speed.
> Ensure count-in and one-time-midi are completed correctly

- src/AlphaTabApiBase.ts
Fixes #896
Ensures the transposition pitches are applied to the score not only when the score changes but also when settings are updated and new renderings are initiated. This allows more of an on-the-fly transposition.
> Update transposition pitches not only on score change

- src.csharp/AlphaTab.Test/Test/Globals.cs
- src.kotlin/alphaTab/alphaTab/build.gradle.kts
- src.kotlin/alphaTab/alphaTab/src/androidTest/kotlin/alphaTab/test/Globals.kt
- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #875 
Adds the ability to specify minor keys in alphaTab. Major keys can also be explicitly stated.
> Add minor keys

- src/model/Beat.ts
- test/model/Beat.test.ts
> Fix beat removeNote function keeping stringLookup reference

- src/platform/javascript/AlphaTabWorkerScoreRenderer.ts
- src/rendering/ScoreRenderer.ts
- src/rendering/utils/BarBounds.ts
- src/rendering/utils/MasterBarBounds.ts
Fixes #959
Beats were not sorted by the x-axis like expected and the finish operation was not called. Seems some stuff got lost over time. 
Mainly affects multi-voice/-staff/-track display.
> Ensure correct BoundsLookup state

- src/importer/MusicXmlImporter.ts
- src/midi/MidiFileGenerator.ts
- test-data/musicxml3/first-bar-tempo.musicxml
- test/audio/MidiFileGenerator.test.ts
- test/importer/MusicXmlImporter.test.ts
Fixes #988 
1. Ensure we update the `score.tempo` when we parse the first masterbar in MusicXML
2. Ensure we respect tempo changes from `score.tempo` in the first masterbar.
> Handle first MasterBar Tempo changes correctly

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Implements #505
Added the brush parsing to alphaTex.
The current approach for default values is to ensure that brushes don't play too slow, and letting arpeggios play evenly across the duration. It for sure feels like not all of the timings below are "correct" and need tweaking.
Here is some tex i used for testing:
```
.
\tempo 90
(1.1 2.2 3.3 4.4).4{bd 60} (1.1 2.2 3.3 4.4).8{bu 60} (1.1 2.2 3.3 4.4).2{ad 60} (1.1 2.2 3.3 4.4).16{au 60} r |
(1.1 2.2 3.3 4.4).4{bd 120} (1.1 2.2 3.3 4.4).8{bu 120} (1.1 2.2 3.3 4.4).2{ad 120} (1.1 2.2 3.3 4.4).16{au 120} r |
(1.1 2.2 3.3 4.4).4{bd 240} (1.1 2.2 3.3 4.4).8{bu 240} (1.1 2.2 3.3 4.4).2{ad 240} (1.1 2.2 3.3 4.4).16{au 240} r |
(1.1 2.2 3.3 4.4).4{bd} (1.1 2.2 3.3 4.4).8{bu} (1.1 2.2 3.3 4.4).2{ad} (1.1 2.2 3.3 4.4).16{au} r |
(1.1 2.2 3.3 …
```
> Add brushes and arpeggio to alphaTex

- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/HtmlElementContainer.ts
- src/platform/javascript/ScalableHtmlElementContainer.ts
Fixes wrong cursor placement when using browser zoom (detected as part of 1.2.3 testing)
The problem with 1x1px elements being scaled using transforms is the order how the browser applies the browser zoom (not pinch zoom). First the 1x1px element is scaled to the zoom level and then the scale is applied. on a 1x1px element, it will stay a 1x1px element on the browser zoom because on those pixel sized elements no fractions are possible. Then the scale is applied keeping the element always on the 100% zoom level not matching the music sheet. 
As a fix we use now a 100x100px element for cursors and selections which is then scaled correctly. This way the 100x100px element gives us enough zoom options to scale along the browser zoom.
> Adjust ui element positioning to support browser scaling

- src/midi/MidiFileGenerator.ts
- test/audio/MidiFileGenerator.test.ts
Fixes #1011 
Ensures vibrato audio is generated just like displayed on tied notes.
> Generate vibrato on tied notes like displayed

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
General maintenance related 
Updates the GHA workflows to use the latest action versions. Switch to linux not possible due to deterministic needs on visual test suite.
> Change runner and update workflows

- CONTRIBUTING.md
- README.md
Various changes and syntax style fixes.
Moved build status to top and added link.
**Edit:** Added changes to CONTRIBUTING aswell. Added link to docs page.
> Clean up README

- src.compiler/AstPrinterBase.ts
- src/importer/AlphaTexImporter.ts
- src/midi/GeneralMidi.ts
- src/model/ModelUtils.ts
* Simplified logic and added comments in ATX importer. + Other small fixes
> Various code improvements. Small AlphaTexImporter bugfix.

- src/midi/MidiPlaybackController.ts
- test/audio/MidiPlaybackController.test.ts
Fixes #1046 
When starting a fresh new group, we have to clear any potential alternate endings from previous bars.
> Fix wrong repeats on alternate endings

- src/AlphaTabApiBase.ts
- src/midi/MidiTickLookup.ts
Fixes #1047
`absolutePlaybackPosition` does not respect repeats but just goes linearly across bars. This leads to wrong cursor placement (which self-heals right afterwards). This change ensures we use the real playback position respecting repeats where relevant.
> Ensure we respect repeats on getting beat playback position

- src/AlphaTabApiBase.ts
- src/rendering/ScoreRenderer.ts
Fixes #1090
ICanvas used to provide some results when render finished but not it doesn't. Due to that the onRenderFinished signals an empty render result to the UI facade to be displayed. The problem is that the new placeholder system does not clear placeholders to get a smoother UI: It is better to keep an old render result before the new one becomes available. 
The problem is if the placeholder content has a 0 width and height. We would need to clean the placeholder from its old content because it will never become visible. To avoid implementing this code in every UI facade we simply not signal empty results to the UI facade anymore which will ensure placeholders are only filled with proper content or are removed.
> Ensure we do not signal the UI facade for empty partials

- src.compiler/csharp/CSharpAstTransformer.ts
- src.compiler/kotlin/KotlinAstTransformer.ts
- src/Logger.ts
- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
- Implements #1044 
- Adds more details and logic to display better error messages overall:
- Add a specific error for when a string is opened but never closed before EOF.
- Only show incorrect values of _syData when it makes sense.
- lastValidSpot makes sure the error message points out where the incorrect syntax started instead of where the importer discovered the error.
> AlphaTex Error improvements. Line/col numbers.

- .github/workflows/publish.yml
Fixes #1112 
(Run # 8 is a cache miss, therefore the two publish jobs get run. Run # 9 is a cache hit, so both publish jobs are skipped.)
- Fixed caching
- Fixed DRY
- Adjusted schedule to 10 minutes past midnight to reduce load
- Bumped setup-java to v3 (I have no idea if this breaks something)
> Fix and cleanup Publish workflow

- src/platform/javascript/BrowserUiFacade.ts
Fixes #1147
Prevents requesting the rendering of the same partial multiple times. If the same partial is requested to be rendered multiple times this messes with the positioning of ties. 
iOS can sometimes signal the visibility change of the same element multiple times. If this happens things break. By preventing multiple render requests we not only improve performance but also fix the problem with the ties.
> Prevent duplicate render requests of partials

- src/synth/AlphaSynth.ts
Fixes #1140
The check whether the count-in is done was wrong in case of playback ranges.
> Fix broken count-in on playback ranges

- src/midi/AlphaSynthMidiFileHandler.ts
- src/midi/IMidiFileHandler.ts
- src/midi/MidiFileGenerator.ts
- src/midi/MidiUtils.ts
- test/audio/FlatMidiEventGenerator.ts
- test/audio/MidiFileGenerator.test.ts
Fixes #1150 
We do a 2 stage velocity calculation for notes, first we adjust the dynamics and then later convert it to the midi note velocity. But this can exceed the valid value range of dynamics. 
This can lead to problems on platforms like Kotlin exceeding the valid enum values as they are strictly checked. 
This PR changes the generation to a simple direct velocity computation to fix it.
> Fix dynamics generation exceeding value range

- src/importer/PartConfiguration.ts
Fixes #1238
The understanding of the PartConfiguration structure was wrong. I analyzed deeper and checked whats going on in this file and how it is structured. Findings are documented and the reading/writing logic was adjusted. 
Hard to do automatic testing because we cannot launch Guitar Pro in our tests for verifying what we do.
> Analyze, Document and Fix PartConfiguration handling

- src/importer/GpifParser.ts
Fix the import of some gpx files that uses Float instead Double node on XProperties
Example of gpx xml part that was throwing error
```xml
<Bar id="29">
<Clef>G2</Clef>
<Voices>26 -1 -1 -1</Voices>
<XProperties>
<XProperty id="1124139520">
<Float>1.07818</Float>
</XProperty>
</XProperties>
</Bar>
```
I was trying to import a gpx file with an error, tracing the error I found that was due to a child node from XProperties that the importer only looks for the Double node, but I found out in gpx that it can also be Float
Look for both nodes types (Double and Float) to get the bar scale value
> Fix: allow the import of gpx files that use displayScale as Float xml node

- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.kotlin/alphaTab/alphaTab/src/androidMain/kotlin/alphaTab/platform/android/AndroidThreadAlphaSynthWorkerPlayer.kt
- src/AlphaTabApiBase.ts
- src/midi/MidiFileGenerator.ts
- src/model/Note.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/synthesis/TinySoundFont.ts
Fixes #896
Instead of applying the transposition pitches directly to the midi, we generate now the midi without transposal and pass the transposition pitches separately to the synth. 
A new synth API allows then modifying the pitches on-the fly and we use this API in applySettings.
> Allow dynamic change of transposition pitches. 

- src.csharp/AlphaTab.Test/Test/Globals.cs
- src.csharp/AlphaTab/Collections/List.cs
- src.csharp/AlphaTab/Core/EcmaScript/Set.cs
- src.kotlin/alphaTab/alphaTab/src/commonMain/kotlin/alphaTab/core/ecmaScript/Set.kt
- src/AlphaTabApiBase.ts
- src/midi/BeatTickLookup.ts
- src/midi/MasterBarTickLookup.ts
- src/midi/MidiFileGenerator.ts
- src/midi/MidiTickLookup.ts
- test/audio/MidiTickLookup.test.ts
Fixes #1281
This PR reworks largely how the `MidiTickLookup` works internally. 
- We slice now differently the masterbars into sections where one or multiple beats are played. 
- Within this new slices we then try to lookup based on a given tick and hint the positions. 
For the sake of stability I didn't attempt any code level optimizations but kept the code rather readable.
> Rework Tick Lookup mechanism for cursor placement and highlighting. 

- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src.csharp/AlphaTab.Windows/WinForms/AlphaSkiaUtil.cs
- src.csharp/AlphaTab.Windows/WinForms/WinFormsUiFacade.cs
- src.csharp/AlphaTab.Windows/Wpf/AlphaSkiaImageSource.cs
- src.csharp/AlphaTab.Windows/Wpf/WpfUiFacade.cs
- src.csharp/AlphaTab/Platform/Skia/AlphaSkiaBridge/AlphaSkiaBridge.cs
Fixes #1288
* Fix problems on displaying alphaSkia rendered images on .net 
* Allow access to image wrapper type for unwrapping in custom code. 
* Fix wrong reporting of played samples leading to wrong cursor positioning (fixes #1288)
> Fix .net related problems with alphaSkia, fix player related problems

- src/synth/AlphaSynth.ts
Fixes #1298
There was a race condition between the audio workers and the main synthesizer components when the playback finished. The sequence was roughly:
1. The last samples of the song are synthesized and the sequencer finishes. 
2. The audio output still has samples to play so it continues, but we stop synthesizing new samples as we are finished. 
3. The last samples are played the synthesizer marks the playback as finished. 
4. At the same time like 3. the output already has requested again new samples for being played.
5. The output is stopped as part of 3. 
6. As the output already requested samples we start synthesizing the related buffers. 
7. We the midi sequencer is out of sync with the main synth time. 
8. When we now start playing again the midi sequencer finishes too early …
> Fix harsh noise by only synthesizing samples while playing

- src/AlphaTabApiBase.ts
- src/midi/BeatTickLookup.ts
- src/midi/MasterBarTickLookup.ts
- src/midi/MidiFileGenerator.ts
- src/midi/MidiTickLookup.ts
- test/audio/MidiTickLookup.test.ts
Fixes #1331
Handles additional cases and scenarios for the tick lookup
> Additional cases for new tick lookup

- src/midi/BeatTickLookup.ts
- src/midi/MasterBarTickLookup.ts
- src/midi/MidiTickLookup.ts
- test/audio/MidiTickLookup.test.ts
Fixes #1339
Fixes the two scenarios described in the bug report: 
* We need to accept the beat of empty voices in the lookup to have the cursor considered. 
* We need to ensure we add pre-beat grace notes also to the previous bar lookup if possible
* We need to ensure we take the original beat playback start for the visibility check, not the slice start.
> Handle empty bars and pre-beat grace notes on new lookup logic

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
Stumbled upon a piece that has a BPM of 112.3(!), so I propose this change where the tempo number can also be a float in a string. (using additional dots and number breaks the parser in edge cases)
> feat(alphaTex): allow specifying tempo as a float in a string

- rollup.config.ts
- src/Environment.ts
- src/alphaTab.main.ts
- src/webpack/AlphaTabAudioWorklet.ts
- src/webpack/AlphaTabWebPackPlugin.ts
- src/webpack/AlphaTabWebPackPluginOptions.ts
- src/webpack/AlphaTabWebWorker.ts
- src/webpack/AlphaTabWorkerDependency.ts
- src/webpack/AlphaTabWorkerRuntimeModule.ts
- src/webpack/AlphaTabWorkletStartRuntimeModule.ts
- src/webpack/Utils.ts
- test/bundler/WebPack.test.ts
- types/webpack/Identifier.d.ts
- types/webpack/MakeSerializable.d.ts
- types/webpack/ModuleTypeConstants.d.ts
- types/webpack/index.d.ts
Fixes #1396 
Adjusts the WebPack plugin further to be compatible with Angular out of the box.
1. We remove the feature for custom chunking and leave this up to the user or frameworks to handle. 
2. We handle WebWorkers ourselves (reusing some parts of the official worker plugin) to bypass the Angular config.
> Handle WebWorkers ourselves for Angular

- package.json
Fixes #1503 
Do not pack source maps to NPM package, they reference the TS files not shipped in the package.
> fix: Source Maps should not be shipped in NPM package

- package-lock.json
- package.json
- src/vite/copyAssetsPlugin.ts
- src/webpack/AlphaTabWebPackPlugin.ts
- test/bundler/Vite.test.ts
- test/bundler/WebPack.test.ts
Fixes #1577 
Seems there are some inconsistencies across node versions when it comes to the paths when traversing directories. With this PR we use the parentPath if available.
> fix: Use ParentPath on file copy if available

- src/platform/javascript/AlphaSynthAudioWorkletOutput.ts
- src/platform/javascript/AlphaSynthScriptProcessorOutput.ts
- src/platform/javascript/AlphaSynthWorkerSynthOutput.ts
Relates to #1599
Improves the handling of audio worklet buffers to not exceed the buffer boundaries and stop the audio worklet after finish. 
Not clear if it fully fixes the problems but if should improve some bits
> fix: Ensure we stay within buffer boundaries and stop worklet

- src/synth/AlphaSynth.ts
- src/synth/MidiFileSequencer.ts
- src/synth/synthesis/TinySoundFont.ts
Fixes #1599 
We currently have a hard stop when we reach the end of the song. This leads to a cut-off on the samples and results in weird clicking noises. This PR changes the stop sequence of the synthesizer to:
1. Request a fast stop of all voices being played (not instantly)
2. Waiting for all voices to really stop providing samples before finishing
This way we have a smooth ramp-down of the audio (still fast though).
> fix: Ensure smooth synth ending

- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidThreadAlphaSynthWorkerPlayer.kt
- src/AlphaTabApiBase.ts
- src/platform/javascript/AlphaSynthWebWorker.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/synthesis/TinySoundFont.ts
Fixes #1488
adds additional APIs for changing the transposition pitches of tracks (and channels) live. These pitches are respected independently from the transpositions already applied on tracks (e.g. via settings).
> feat: add live transposition pitch changes

- src/platform/javascript/HtmlElementContainer.ts
Fixes #1766 
Corrected to use correct scroll offset causing vertical scrolling to break.
> fix: Scrolling Issue with ScrollMode.OffScreen

- src/synth/synthesis/TinySoundFont.ts
Fixes #1827
With #1489 we configured now wrongly the range of samples to play. Adjusting the range relatively seemed to work for most samples but for some others it was incorrect. Now we simply set the range to the whole sample buffer to avoid any problems.
> fix: No drum sounds

- src.csharp/AlphaTab/Core/EcmaScript/RegExp.cs
- src/generated/model/NoteCloner.ts
- src/generated/model/NoteSerializer.ts
- src/importer/AlphaTexImporter.ts
- src/importer/Gp3To5Importer.ts
- src/importer/GpifParser.ts
- src/model/Beat.ts
- src/model/ModelUtils.ts
- src/model/Note.ts
- src/model/Staff.ts
- src/model/Track.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/rendering/glyphs/AlternateEndingsGlyph.ts
- src/synth/AlphaSynth.ts
- src/synth/SynthHelper.ts
- test/importer/AlphaTexImporter.test.ts
- test/model/ComparisonHelpers.ts
- test/visualTests/features/EffectsAndAnnotations.test.ts
- test/visualTests/features/MusicNotation.test.ts
Fixes #1484
Adds a wide range of missing model features to alphaTex.
> feat(alphatex): Add missing model features

- src/importer/AlphaTexImporter.ts
- test/importer/AlphaTexImporter.test.ts
alphaTex did reset the clef on every new bar to the default which makes it cumbersome to write notation correctly. with this change alphaTex keeps the clef from the previous bar.
> feat(alphatex): Remember clefs

- src.kotlin/alphaTab/android/src/test/java/alphaTab/core/TestGlobals.kt
- src/importer/AlphaTexImporter.ts
- src/midi/MidiFileGenerator.ts
- test/audio/MidiFileGenerator.test.ts
- test/importer/AlphaTexImporter.test.ts
Fixes a problem detected during release testing and documenting. The live-transposition pitches change broke something on pre-applied transpositions. This PR fixes these problems.
> fix: Wrong transpositions

- src/Environment.ts
- src/alphaTab.main.ts
Fixes #1917
Attempt creating blob workers on ESM as fallback to prevent CORS problems when importing alphaTab from CDNs.
> fix: Create blob worker for ESM to allow easier CDN usage.

- rollup.config.vite.ts
- rollup.config.webpack.ts
- src/vite/copyAssetsPlugin.ts
- src/webpack/AlphaTabWebPackPlugin.ts
Improves resolving the alphaTab location by asking node where to find it. Eliminates the need of manually setting paths in special environments.
> feat(bundler): Improve resolving of alphaTab

- src/platform/svg/SvgCanvas.ts
- test/visualTests/issues/BrokenRenders.test.ts
Detected while testing and documenting: If you use font families with quotes, it breaks the SVG attribute quotes. This PR changes the attribute to single quotes.
> fix(svg): Wrong style quoting with spaced fonts

- playground-template/control-template.html
- playground-template/control.mjs
- src.compiler/csharp/CSharpAstTransformer.ts
- src.compiler/csharp/CSharpEmitterContext.ts
- src.compiler/kotlin/KotlinAstTransformer.ts
- src.csharp/AlphaTab.Test/AlphaTab.Test.csproj
- src.csharp/AlphaTab.Windows/NAudioSynthOutput.cs
- src.csharp/AlphaTab/AlphaTab.csproj
- src.csharp/AlphaTab/Platform/CSharp/AlphaSynthWorkerApiBase.cs
- src.csharp/AlphaTab/Platform/CSharp/ManagedThreadAlphaSynthWorkerApi.cs
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Promise.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidAudioWorker.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidSynthOutput.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidThreadAlphaSynthWorkerPlayer.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidUiFacade.kt
- src.kotlin/alphaTab/android/src/test/java/alphaTab/TestPlatformPartialsImpl.kt
- src/AlphaTabApiBase.ts
- src/platform/javascript/AlphaSynthWebAudioOutputBase.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaSynthWorkerSynthOutput.ts
- src/synth/AlphaSynth.ts
- src/synth/IAlphaSynth.ts
- src/synth/ISynthOutput.ts
- src/synth/index.ts
- test/audio/TestOutput.ts
Fixes #1904
Adds the described abstraction of output devices with necessary APIs to change output devices dynamically. 
Browser support is still limited, but if they have the related APIs implemented alphaTab will work.
> feat(player): Allow changing of output device

- .github/workflows/build.yml
This is faster than `actions/cache` for Gradle builds.
https://github.com/gradle/actions?tab=readme-ov-file#the-setup-gradle-action
> Caching Kotlin things with gradle/actions/setup-gradle

- src.compiler/AstPrinterBase.ts
- src.compiler/csharp/CSharpAst.ts
- src.compiler/csharp/CSharpAstPrinter.ts
- src.compiler/csharp/CSharpAstTransformer.ts
- src.compiler/csharp/CSharpEmitterContext.ts
- src.compiler/kotlin/KotlinAstPrinter.ts
- src.compiler/kotlin/KotlinEmitterContext.ts
- src.csharp/AlphaTab/Collections/List.cs
- src.csharp/AlphaTab/Core/EcmaScript/Iterable.cs
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Iterable.kt
- src/importer/CapellaParser.ts
- src/importer/GpifParser.ts
- src/importer/MusicXmlImporter.ts
- src/xml/XmlNode.ts
Preparation for #1887
Introduces a `childElements` iterator to reduce a bit the repetitive checks in the XML based importers.
> refactor: Add childElements iterator for XML parsing

- .github/ISSUE_TEMPLATE/bug_report_form.yml
- src.compiler/typescript/AlphaTabGenerator.ts
- src.csharp/AlphaTab/Environment.cs
- src.kotlin/alphaTab/android/src/main/java/alphaTab/EnvironmentPartials.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidEnvironment.kt
- src/AlphaTabApiBase.ts
- src/Environment.ts
Provides an easier/improved way to grab the version and environment info for bug reports.
> chore: Easier way to provide exact version and environment info.

- src.csharp/AlphaTab.Test/TestPlatform.cs
- src.csharp/AlphaTab/Core/Dom/TextDecoder.cs
- src.csharp/AlphaTab/Core/EcmaScript/ArrayBuffer.cs
- src.csharp/AlphaTab/Core/EcmaScript/DataView.cs
- src.csharp/AlphaTab/Core/EcmaScript/Int16Array.cs
- src.csharp/AlphaTab/Core/EcmaScript/Uint8Array.cs
- src.csharp/AlphaTab/Io/TypeConversions.cs
- src.csharp/AlphaTab/Platform/Skia/AlphaSkiaBridge/AlphaSkiaBridge.cs
- src.kotlin/alphaTab/android/build.gradle.kts
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/DataView.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Float32Array.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Int16Array.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Int32Array.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/core/ecmaScript/Uint8Array.kt
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidAudioWorker.kt
- src.kotlin/alphaTab/gradle/libs.versions.toml
- src/synth/soundfont/Hydra.ts
Relates to #1959 
Fixes some problematic bits on the android env:
1. Font and SoundFont were not embedded anymore
2. The sample decoding was wrong due to BigEndian platform endianess.
> fix(android): Incorrect sample decoding and missing assets

- package.json
- scripts/prepack.mjs
Fixes #2045 #2044
Node.js seems to have a bit a wierd behavior when it comes to loading modules. Despite the `exports` section defining (seemingly) the format and path for it, it behaves different.
Likely this started to become a problem with Node 22 which added support to load ESM files from CommonJS files:
The conditional `export` is only used to resolve the path to the file. But then if `.js` is used as extension, they load the file based on `type` in the parent package.json. 
We have `type: module` as we mainly use ESM stuff in our own repo and a lot of tooling, and also node itself when executing scripts, rely on this. Again some tooling do not support extensions like `.mts`. 
Using `.cjs` is also not fully correct as alphaTab itself is rather a UMD than a CJS only. The extension …
> build: Publish NPM package with type commonjs

- src/rendering/BarRendererBase.ts
- src/rendering/NumberedBarRendererFactory.ts
- src/rendering/glyphs/NumberedSlurGlyph.ts
- src/rendering/glyphs/ScoreBendGlyph.ts
- src/rendering/glyphs/ScoreSlideLineGlyph.ts
- src/rendering/glyphs/ScoreWhammyBarGlyph.ts
- src/rendering/glyphs/TabBendGlyph.ts
- src/rendering/glyphs/TabSlideLineGlyph.ts
- src/rendering/glyphs/TabSlurGlyph.ts
- src/rendering/glyphs/TabWhammyBarGlyph.ts
- src/rendering/glyphs/TieGlyph.ts
- src/rendering/staves/RenderStaff.ts
- src/rendering/staves/StaffSystem.ts
- src/rendering/utils/AccidentalHelper.ts
Fixes #2050
1. Use the correct staffId for the numbered bar renderer staff.
2. rename plural `staveId` to singluar `staffId`
> fix: Wrong staff ID for numbered bar renderer

- src/importer/AlphaTexImporter.ts
- src/model/PercussionMapper.ts
- src/rendering/utils/AccidentalHelper.ts
- test/exporter/Gp7Exporter.test.ts
- test/importer/AlphaTexImporter.test.ts
Fixes #2056 
We wrongly used the midi number as percussion articulation on notes. While this worked internally in alphaTab thanks to some fallback mechanism, it fails when we export to GP.
Now we collect the articulations in the track and reference with the currect index. This way the values will match what GP expects.
> fix(alphatex): Wrong instrument articulations for export

- src/synth/AlphaSynth.ts
Fixes #2076
It can happen that the synth keeps producing samples endlessly even though the end of the song is reached. The output keeps requesting samples, and the synth keeps producing them (and the voices stay active). 
With the adaptions in this PR we ensure we signal the synth to stop all voices. The ramp down should stil be smooth enough to avoid crackling noises on the output.
> fix: Ensure synth stops voices when end is reached

- playground-template/control.mjs
- playground-template/youtube.css
- playground-template/youtube.html
- src/AlphaTabApiBase.ts
- src/synth/ExternalMediaPlayer.ts
Fixes #1961
Adds a first implementation and demo for integrating alphaTab with an external media backing track. It adds a separate handler developers need to implement and pass into alphaTab.
> feat: Add basic implementation for external media backing track

- src.kotlin/alphaTab/android/src/main/java/alphaTab/collections/List.kt
- src/synth/AlphaSynth.ts
- src/synth/BackingTrackPlayer.ts
- src/synth/ds/Queue.ts
- src/synth/synthesis/TinySoundFont.ts
Fixes #1959
Fixes problems with the handling of queues and sublists in Kotlin which can cause Stack Overflows due to wierd internal ArrayList behaviors.
> fix: Fix queue and list handling for kotlin

- playground-template/control.mjs
- playground-template/youtube.html
- src.csharp/AlphaTab.Windows/DelegatedEventEmitter.cs
- src.csharp/AlphaTab/EventEmitter.cs
- src.kotlin/alphaTab/android/src/main/java/alphaTab/platform/android/AndroidUiFacade.kt
- src/AlphaTabApiBase.ts
- src/EventEmitter.ts
- src/midi/MidiFileGenerator.ts
- src/platform/javascript/AlphaSynthWebWorkerApi.ts
- src/platform/javascript/AlphaTabApi.ts
- src/platform/javascript/AudioElementBackingTrackSynthOutput.ts
- src/platform/javascript/HtmlElementContainer.ts
- src/synth/AlphaSynth.ts
- src/synth/AlphaSynthWrapper.ts
- src/synth/MidiFileSequencer.ts
- src/synth/synthesis/TinySoundFont.ts
Fixes #2078
Improves and refactors quite some bits around the player and cursor handling. 
1. We need a final sync point at the end of the song which matches the BPM (not the song end) for correct synchronization with guitar pro files. 
2. The general tempo and sync point handling is not better integrated. Tempo and sync points update as part of the playback (time position update) and not the synth part. This is more accurate and avoids some cursor speed problems on tempo changes. 
3. The time to tick position translation is now more efficeint thanks to incremental updates of the current tempo change. 
4. Removed a small playground error when handling backing tracks.
5. Smooth the cursor by letting it animate 2-times the distance in double the time. This avoids stopping cursors when its …
> feat(player): Cursor fine-tuning

- src/importer/MusicXmlImporter.ts
- test-data/musicxml4/2102-corrupt-direction.xml
- test/importer/MusicXmlImporter.test.ts
- test/importer/__snapshots__/musicxmlimporter.test.ts.snap
Fixes #2102
In old MuseScore versions exported MusicXML `direction-type` might be empty. This PR handles this edge case for the importer.
Despite the schema requiring it: 
https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/direction-type/
https://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-direction-type.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7CElements%7Cdirection%7C_____22
Related bug on MuseScore side: https://musescore.org/en/node/293441
> fix(musicxml): Allow empty direction-type

- src.compiler/typescript/Serializer.setProperty.ts
- src.compiler/typescript/Serializer.toJson.ts
- src/CoreSettings.ts
- src/Environment.ts
- src/RenderingResources.ts
- src/alphaTab.core.ts
- src/generated/CoreSettingsJson.ts
- src/generated/CoreSettingsSerializer.ts
- src/generated/RenderingResourcesJson.ts
- src/generated/RenderingResourcesSerializer.ts
- src/model/Font.ts
- src/platform/javascript/BrowserUiFacade.ts
- src/platform/javascript/Html5Canvas.ts
- test/bundler/Vite.test.ts
- test/visualTests/VisualTestHelper.ts
Fixes #2113
Allows more flexible configuration of the SmuFL web font used in alphaTab. (e.g. loading bravura from a data url). 
Note: We do not support other SmuFL fonts other than bravura with this improvement. This is part of #1949 where we'll need to accept metadata to size and position things correctly. But the change is taking a small step towards this.
> feat: Add option for custom smufl font sources

- src/AlphaTabApiBase.ts
- src/midi/MidiFileGenerator.ts
- src/synth/MidiFileSequencer.ts
Relates to #1961 
Fixes some more findings around the external cursor api changes:
* The beat cursor was animating too far in some cases. We now respect the animation hint whether animation should only go to the end of the bar (e.g. on repeats or song ends). 
* Sync points were generated double after the refactoring
* The double update of sync points in the midi sequencer was wrong as it mixed the backing track and alphatab time axis.
> fix: External Cursor API related problems

- src.compiler/csharp/CSharpAstTransformer.ts
- src/importer/AlphaTexImporter.ts
- src/importer/ScoreLoader.ts
- src/importer/_barrel.ts
- src/model/Bar.ts
- src/model/MasterBar.ts
- src/model/ModelUtils.ts
- test/audio/MidiPlaybackController.test.ts
- test/importer/AlphaTexImporter.test.ts
- test/importer/__snapshots__/AlphaTexImporter.test.ts.snap
Fixes #2126
Adds alphaTex support for sync points. Also it exposes the alphaTex importer for easier external use.
> feat: Sync Points for alphaTex

- src/midi/MidiFileGenerator.ts
- test/audio/SyncPoint.test.ts
- test/audio/__snapshots__/SyncPoint.test.ts.snap
Needed for the media sync editor to avoid code duplication. Adds a parameter which allows creation of a fresh set of sync points based on the synth timing and the song tempo changes.
> feat: Add option to create fresh sync points

- package-lock.json
- package.json
- src.csharp/AlphaTab.Test/AlphaTab.Test.csproj
- src.csharp/AlphaTab.Windows/AlphaTab.Windows.csproj
- src.csharp/AlphaTab/AlphaTab.csproj
- src.kotlin/alphaTab/gradle/libs.versions.toml
Fixes #2205
Updates alphaSkia to the version which has the required fix for the rendering issues on Android. Basically Android is not guaranteeing a zero-terminator on strings and alphaSkia needs to use the explicitly provided string length.
> fix: Update alphaSkia to 3.4.135
